### ISSUE TITLE
NPM outdated

### ISSUE THREAD

**Issue by ncul777** [silverwind/oui-data#3]
Hi, I noticed that npm currently has 1.1.6 (3 months old). The latest tag on github is 1.1.62.

Would it be possible to push the latest version to npm? And push on every update, or at least a regular basis e.g. weekly or even monthly?

Thanks

**Comment by silverwind** [comment]
There is something wrong in the publish action:

https://github.com/silverwind/oui-data/actions/runs/8106693136/job/22157032194

I manually published `oui-data@1.1.62` now, will investigate later.

**Comment by ncul777** [comment]
Thanks

**Comment by silverwind** [comment]
It's working again, was a problem with the token.
